<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="9" total="10" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-12T00:07:25 GST" name="Default suite" finished-at="2022-05-12T00:08:48 GST" duration-ms="82902">
    <groups>
      <group name="Check24-Regression-TestCases">
        <method signature="Check24_TestsSuites.Check24_TestCases_10()[pri:10, instance:com.check24.selenium.tests.Check24_TestsSuites@11392934]" name="Check24_TestCases_10" class="com.check24.selenium.tests.Check24_TestsSuites"/>
      </group> <!-- Check24-Regression-TestCases -->
    </groups>
    <test started-at="2022-05-12T00:07:25 GST" name="Default test" finished-at="2022-05-12T00:08:48 GST" duration-ms="82902">
      <class name="com.check24.selenium.tests.Check24_TestsSuites">
        <test-method is-config="true" signature="BeforeSuite()[pri:0, instance:com.check24.selenium.tests.Check24_TestsSuites@11392934]" started-at="2022-05-12T00:07:24 GST" name="BeforeSuite" finished-at="2022-05-12T00:07:25 GST" duration-ms="795" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeSuite -->
        <test-method signature="Check24_TestCases_10()[pri:10, instance:com.check24.selenium.tests.Check24_TestsSuites@11392934]" started-at="2022-05-12T00:07:25 GST" name="Check24_TestCases_10" finished-at="2022-05-12T00:08:48 GST" duration-ms="82848" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.check24.selenium.utils.Utilities.TakeScreenshot(Utilities.java:608)
at com.check24.selenium.tests.Check24_TestsSuites.Check24_TestCases_10(Check24_TestsSuites.java:342)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Check24_TestCases_10 -->
        <test-method is-config="true" signature="beforeTestMethod(java.lang.reflect.Method)[pri:0, instance:com.check24.selenium.tests.Check24_TestsSuites@11392934]" started-at="2022-05-12T00:08:48 GST" name="beforeTestMethod" finished-at="2022-05-12T00:08:48 GST" duration-ms="3" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.check24.selenium.tests.Check24_TestsSuites.Check24_TestCases_10() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestMethod -->
        <test-method is-config="true" signature="AfterSuite()[pri:0, instance:com.check24.selenium.tests.Check24_TestsSuites@11392934]" started-at="2022-05-12T00:08:48 GST" name="AfterSuite" finished-at="2022-05-12T00:08:49 GST" duration-ms="636" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterSuite -->
      </class> <!-- com.check24.selenium.tests.Check24_TestsSuites -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
